# Substituições dinâmicas para tornar o build mais reutilizável
substitutions:
  _SERVICE_NAME: app-clima-n8n-evolution
  _AR_HOSTNAME: southamerica-east1-docker.pkg.dev
  _DEPLOY_REGION: southamerica-east1

steps:
  # 1. Fazer build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      [
        'build',
        '-t',
        '${_AR_HOSTNAME}/${PROJECT_ID}/repositorio-app-clima-n8n/${_SERVICE_NAME}:$SHORT_SHA',
        '.'
      ]

  # 2. Enviar a imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      [
        'push',
        '${_AR_HOSTNAME}/${PROJECT_ID}/repositorio-app-clima-n8n/${_SERVICE_NAME}:$SHORT_SHA'
      ]

  # 3. Fazer o deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        '${_AR_HOSTNAME}/${PROJECT_ID}/repositorio-app-clima-n8n/${_SERVICE_NAME}:$SHORT_SHA',
        '--region',
        '${_DEPLOY_REGION}',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--memory=2Gi',
        '--cpu=2'
      ]

# Registrar a imagem gerada no Artifact Registry
images:
  - '${_AR_HOSTNAME}/${PROJECT_ID}/repositorio-app-clima-n8n/${_SERVICE_NAME}:$SHORT_SHA'

# Configurações adicionais para logging e substituições flexíveis
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

# Adicionando permissão para acessar o Secret Manager
availableSecrets:
  secretManager:
    - versionName: "projects/152190816099/secrets/senha-gee/versions/latest"
      env: "GOOGLE_APPLICATION_CREDENTIALS"
