# Substituições dinâmicas para tornar o build mais reutilizável
substitutions:
  _SERVICE_NAME: app-clima-n8n-evolution
  _AR_HOSTNAME: southamerica-east1-docker.pkg.dev
  _DEPLOY_REGION: southamerica-east1

steps:
  # 1. Fazer build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      [
        'build',
        '--no-cache', # Adicionado para garantir um build "limpo"
        '-t',
        '${_AR_HOSTNAME}/${PROJECT_ID}/repositorio-app-clima-n8n/${_SERVICE_NAME}:$SHORT_SHA',
        '.' # Diretório do Dockerfile
      ]

  # 2. Enviar a imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      [
        'push',
        '${_AR_HOSTNAME}/${PROJECT_ID}/repositorio-app-clima-n8n/${_SERVICE_NAME}:$SHORT_SHA'
      ]

  # 3. Verificar se o serviço já existe
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Check-Service
    entrypoint: 'bash'
    args:
      [
        '-c',
        'if gcloud run services describe ${_SERVICE_NAME} --region=${_DEPLOY_REGION} --platform=managed > /dev/null 2>&1; then echo "Service exists"; else echo "Service does not exist"; fi'
      ]

  # 4. Fazer o deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: 'bash'
    args:
      [
        '-c',
        'if gcloud run services describe ${_SERVICE_NAME} --region=${_DEPLOY_REGION} --platform=managed > /dev/null 2>&1; then
          gcloud run deploy ${_SERVICE_NAME} \
            --image=${_AR_HOSTNAME}/${PROJECT_ID}/repositorio-app-clima-n8n/${_SERVICE_NAME}:$SHORT_SHA \
            --region=${_DEPLOY_REGION} \
            --platform=managed \
            --no-traffic \
            --tag=test \
            --allow-unauthenticated \
            --memory=2Gi \
            --cpu=2;
        else
          gcloud run deploy ${_SERVICE_NAME} \
            --image=${_AR_HOSTNAME}/${PROJECT_ID}/repositorio-app-clima-n8n/${_SERVICE_NAME}:$SHORT_SHA \
            --region=${_DEPLOY_REGION} \
            --platform=managed \
            --allow-unauthenticated \
            --memory=2Gi \
            --cpu=2;
        fi'
      ]

# Registrar a imagem gerada no Artifact Registry
images:
  - '${_AR_HOSTNAME}/${PROJECT_ID}/repositorio-app-clima-n8n/${_SERVICE_NAME}:$SHORT_SHA'

# Configurações adicionais para logging e substituições flexíveis
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

# Adicionando tags para rastreamento e categorização do build
tags:
  - gcp-cloud-build-deploy-cloud-run
  - ${_SERVICE_NAME}